#!/usr/bin/zsh
# Fundamental configuration for all (non-login, non-interactive) shells.
# Exported VALUES will be most probably overwritten by /etc/zprofile;
# as such, this file should contain only early declarations and special exports

# ===== PATH-like arrays with unique values =====
export -U cdpath   # `cd` search path
export -U fpath    # function search path
export -U infopath # `info` search paths
export -U mailpath # file names to check for new mail
export -U path     # binary search path

# ===== Extra PATH-like pairings =====
# -T: bind :-separated variable to an array
# -U: keep values unique
export -TU LD_LIBRARY_PATH  ld_library_path     # dynamic linker search path
export -TU PYTHONPATH       pythonpath          # extra paths for python modules
