#!/usr/bin/zsh
# Late login shell initialization
# Place for automatic setup and similar actions

# Data directories
# => Ensure existence of XDG directories (incl. zsh dir)
mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME/zsh"

# Startup
# => Start X server if one is not running yet
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 && ${commands[startx]} ]]; then
    exec startx
fi
